### ISSUE TITLE
callMethod=onway - wrong_method

### ISSUE THREAD

**Issue by elagin** [rjhdby/MobileServer#11]
Вызываю
{callMethod=onway, id=1950, login=xx, passhash=zzz}
Получаю:
{\"error\":\"wrong_method\"}

Не исправляй пока. Пригодится для обработки ошибок полученных от сервера.

**Comment by elagin** [comment]
Можно исправлять https://github.com/rjhdby/motocitizen/pull/317

**Comment by elagin** [comment]
То же самое с отменой "выехал".

**Comment by rjhdby** [comment]
Не callMethod, а calledMethod

**Comment by rjhdby** [comment]
https://github.com/rjhdby/motocitizen/commit/d92483fbea15d25ac450defa5bc6d57f2d8275af

**Comment by elagin** [comment]
"Выехал" работает.
