### ISSUE TITLE
onway - не выехал

### ISSUE THREAD

**Issue by elagin** [rjhdby/MobileServer#3]
Для поддержки https://github.com/rjhdby/motocitizen/issues/267

**Comment by elagin** [comment]
Булевый что-ли параметр нужен?

**Comment by rjhdby** [comment]
запрос аналогично "выехал", только calledMethod=cancelOnWay

Завтра сделаю на стороне сервера

**Comment by rjhdby** [comment]
47fe2e694e7ffc7b9af4328e9a1e0ae33e30a933

calledMethod=cancelOnWay

Волонтеру выставляется статус статус "cancel"

**Comment by elagin** [comment]
Осталось придумать картинку "я всех обманул и ни куда не поехал".

**Comment by elagin** [comment]
Спасибо.
